app/src/Entity/Question.php
<?php

namespace App\Entity;

use App\Repository\QuestionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=QuestionRepository::class)
 * @ORM\Table(name="questions")
 */
class Question
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $content;

    /**
     * @ORM\ManyToOne(targetEntity=Quiz::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $quiz;

    /**
     * @ORM\OneToMany(targetEntity=QuestionPossibleAnswer::class, mappedBy="question")
     */
    private $question_possible_answer;

    public function __construct()
    {
        $this->question_possible_answer = new ArrayCollection();
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getContent(): ?string
    {
        return $this->content;
    }

    /**
     * @param string $content
     */
    public function setContent(string $content): void
    {
        $this->content = $content;


    }

    /**
     * @return Quiz|null
     */
    public function getQuiz(): ?Quiz
    {
        return $this->quiz;
    }

    /**
     * @param Quiz|null $quiz
     */
    public function setQuiz(?Quiz $quiz): void
    {
        $this->quiz = $quiz;


    }

    /**
     * @return Collection|QuestionPossibleAnswer[]
     */
    public function getQuestionPossibleAnswer(): Collection
    {
        return $this->question_possible_answer;
    }

    /**
     * @param QuestionPossibleAnswer $questionPossibleAnswer
     * @return $this
     */
    public function addQuestionPossibleAnswer(QuestionPossibleAnswer $questionPossibleAnswer): self
    {
        if (!$this->question_possible_answer->contains($questionPossibleAnswer)) {
            $this->question_possible_answer[] = $questionPossibleAnswer;
            $questionPossibleAnswer->setQuestion($this);
        }

        return $this;
    }

    /**
     * @param QuestionPossibleAnswer $questionPossibleAnswer
     * @return $this
     */
    public function removeQuestionPossibleAnswer(QuestionPossibleAnswer $questionPossibleAnswer): self
    {
        if ($this->question_possible_answer->removeElement($questionPossibleAnswer)) {
            // set the owning side to null (unless already changed)
            if ($questionPossibleAnswer->getQuestion() === $this) {
                $questionPossibleAnswer->setQuestion(null);
            }
        }

        return $this;
    }
}

app/src/Entity/QuestionPossibleAnswer.php
<?php

namespace App\Entity;

use App\Repository\QuestionPossibleAnswerRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=QuestionPossibleAnswerRepository::class)
 * @ORM\Table(name="questions_possible_answers")
 */
class QuestionPossibleAnswer
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $content;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_correct;

    /**
     * @ORM\ManyToOne(targetEntity=Question::class, inversedBy="question_possible_answer")
     * @ORM\JoinColumn(nullable=false)
     */
    private $question;


    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getContent(): ?string
    {
        return $this->content;
    }

    /**
     * @param string $content
     */
    public function setContent(string $content): void
    {
        $this->content = $content;


    }

    /**
     * @return bool|null
     */
    public function getIsCorrect(): ?bool
    {
        return $this->is_correct;
    }

    /**
     * @param bool $is_correct
     */
    public function setIsCorrect(bool $is_correct): void
    {
        $this->is_correct = $is_correct;


    }

    /**
     * @return Question|null
     */
    public function getQuestion(): ?Question
    {
        return $this->question;
    }

    /**
     * @param Question|null $question
     *
     */
    public function setQuestion(?Question $question): void
    {
        $this->question = $question;


    }

}

app/src/Entity/Quiz.php
<?php

namespace App\Entity;

use App\Repository\QuizRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=QuizRepository::class)
 * @ORM\Table(name="quizes")
 */
class Quiz
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName(string $name): void
    {
        $this->name = $name;


    }


}

app/src/Controller/PageController.php
<?php
/**
 * Page controller.
 */

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class PageController.
 *
 */
class PageController extends AbstractController
{
    /**
     * Index action.
     *
     * @return \Symfony\Component\HttpFoundation\Response HTTP response
     *
     * @Route(
     *     "/",
     *     name="/",
     * )
     */


    public function page(): Response
    {
        return $this->render('/page/homepage.html.twig');
    }

    /**
     * Homepage action.
     *
     * @return \Symfony\Component\HttpFoundation\Response HTTP response
     *
     * @Route(
     *     "/homepage",
     *     name="homepage",
     * )
     */


    public function homepage(): Response
    {
        return $this->render('/page/homepage.html.twig');
    }

    /**
     * Aboutpage action.
     *
     * @return \Symfony\Component\HttpFoundation\Response HTTP response
     *
     * @Route(
     *     "/about",
     *     name="about",
     * )
     */


    public function about(): Response
    {
        return $this->render('/page/about.html.twig');
    }
    /**
     * Stagespage action.
     *
     * @return \Symfony\Component\HttpFoundation\Response HTTP response
     *
     * @Route(
     *     "/stages",
     *     name="stages",
     * )
     */


    public function stages(): Response
    {
        return $this->render('/page/stages.html.twig');
    }

    /**
     * Accessibilitypage action.
     *
     * @return \Symfony\Component\HttpFoundation\Response HTTP response
     *
     * @Route(
     *     "/accessibility",
     *     name="accessibility",
     * )
     */


    public function accessibility(): Response
    {
        return $this->render('/page/accessibility.html.twig');
    }
}

app/src/Controller/QuestionController.php
<?php
/**
 * Question controller.
 */

namespace App\Controller;


use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class QuestionController.
 *
 */
class QuestionController extends AbstractController
{
    /**
     * Show action.
     *
     * @return \Symfony\Component\HttpFoundation\Response HTTP response
     *
     * @Route(
     *     "/quiz",
     *     methods={"GET","POST"},
     *     name="quiz",
     *
     * )
     */

    public function show(): Response
    {
        $question = $this->getDoctrine()
            ->getRepository('App:Question')
            ->findAll();

        return $this->render(

            'question/show.html.twig',
            array('question' => $question)
        );

    }
    /**
     * Score action.
     *
     * @return \Symfony\Component\HttpFoundation\Response HTTP response
     * @param Request $request
     * @return Response
     * @Route(
     *     "/sendQuiz",
     *     name="sendQuiz",
     *     methods={"GET","POST"},
     * )
     */
    public function sendQuiz(Request $request):Response
    {
    $counter = 0;
    $data_form = implode(",", $request->request->all());
    $data = explode(",",$data_form);
    $length = count($data);

    for ($i=0; $i < $length; $i++) {
        if($data[$i] == '1')
       {
           $counter++;
       }

    }

        return $this->render(

            'question/score.html.twig',
            ['counter' => $counter]
        );
    }
}

app/templates/base.html.twig
<!DOCTYPE html>
<html lang="pl" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}UX DESIGN{% endblock %}</title>
    {% block stylesheets %}
        <link rel="stylesheet" href="{{ asset('css/base.css') }}">
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;300&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

    {% endblock %}
    <div class="backgroundbox">

        <span class="resize">
    <a class="increase"> <i class="fas fa-search-plus"></i></a>
            <a class="reset"><i class="fas fa-search"></i></a>
  <a class="decrease"><i class="fas fa-search-minus"></i></a>

    </span>
    <div class="anim">




        <div class="title">
            <a id="homepage" href="{{ url('homepage') }}">
        <h1>jak projektować <h2 class="title2">strony internetowe</h2></h1>
            </a>
    </div>

        <img class="kwadrat" src="{{ asset('images/kwadratux.png') }}" alt="kwadrat ozdoba"/>

    </div>

    </div>



    <nav class="navi"  >
        {% block nav %}

            <ul>
                <li><a class="nav1"  href="{{ url('homepage') }}" >Strona główna</a></li>
                <li><a class="nav1" href="{{ url('stages') }}">Projektowanie</a></li>
                <li><a class="nav1" href="{{ url('accessibility') }}">Udogodnienia</a></li>
                <li><a class="nav1" href="{{ url('about') }}">O serwisie</a></li>
                <li><a  class="nav1" href="{{ url('quiz') }}">Quiz</a></li>

            </ul>


    </nav>

    <div id="menuToggle">
    <nav class="mobile" >



                <input  type="checkbox" />


                <span></span>
                <span></span>
                <span></span>


                <ul id="menu">
                    <li><a id="link1" href="{{ url('homepage') }}">Strona główna</a></li>
                    <li><a id="link2" href="{{ url('stages') }}">Etapy </a></li>
                    <li><a id="link3" href="{{ url('accessibility') }}">Udogodnienia</a></li>
                    <li><a id="link4" href="{{ url('about') }}">O serwisie</a></li>
                    <li><a id="link5" href="{{ url('quiz') }}">Quiz</a></li>

                </ul>

            {% endblock %}


    </nav>
    </div>
</head>

<body>
<div class="main">

{% block body %}


{% endblock %}

{% block javascripts %}

</div>
    <script src={{ asset('jquery-3.3.1.min.js') }}></script>
    <script src={{ asset('jquery.scrollTo.min.js') }}></script>
    <script src={{ asset('main.js') }}></script>
    <script src={{ asset('text.js') }}></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
{% endblock %}

</div>
<footer>
    <p> Copyright &copy; 2021 by Mariola Podoba. Wszystkie prawa zastrzeżone.</p>

</footer>
</body>
</html>

app/templates/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}

{% endblock %}

{% block body %}

{% endblock %}

app/templates/page/about.html.twig
{% extends 'base.html.twig' %}

{% block title %}

{% endblock %}
{% block stylesheets %}
 {{ parent() }}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ asset('css/about.css') }}">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&display=swap" rel="stylesheet">
    <script src="https://use.fontawesome.com/ce01bab2aa.js"></script>
{% endblock %}
{% block body %}
    <h1 class="h1">
       Informacje o serwisie
    </h1>
    <h2>Czym jest ta strona?</h2>
    <div class="about">


        <div class="aboutcontent">
        <p>Autorem niniejszego serwisu jest Mariola Podoba.</p>
        Serwis ten stanowi integralną część pracy licencjackiej (kierunek: Elektroniczne Przetwarzanie Informacji), przygotowanej pod kierunkiem prof. dra. hab. Jerzego Koniora, na Wydziale Zarządzania i Komunikacji Społecznej Uniwersytetu Jagiellońskiego.
    </div>
    </div>
    <div class="sources">
        <h2>Źródła informacji</h2>
        <div class="aboutcontent2">
            <p>Autorskie grafiki zostały wykonane w programach CorelDRAW, Inkscape lub Canva.</p>
        <p>Wszystkie nieautorskie zdjęcia i obrazki umieszczone na stronie pochodzą z darmowych banków zdjęć, są wykorzystane legalnie i nie wymagają oznaczania. Załączam mimo wszystko bezpośrednie linki do obrazków.</p>
        <h3>Strona główna</h3>
        <ul>
            <h4>Obrazek w tle:</h4>
            <li> <a href='https://www.pexels.com/th-th/photo/733852/ '>pexels</a></li>
            <h4>Obrazki pomiędzy tekstem:</h4>
            <li> <a href='https://pixabay.com/ja/illustrations/意思決定-脳-中心部-心-4083469/'>pixabay </a></li>
            <li> <a href='https://it.freepik.com/vettori-gratuito/video-tutorial-di-progettazione-grafica-corso-di-arte-tradizionale-su-internet-masterclass-online-di-pittore-corso-di-web-designer-a-distanza-pittura-e-learning-educazione_12083109.htm'>freepik</a></li>
            <li> <a href='https://www.pexels.com/photo/hands-of-people-reaching-to-each-other-5541019/'>pexels</a></li>
            <li> <a href='https://www.freepik.es/vector-gratis/ilustracion-concepto-proceso-diseno_13662975.htm#page=1&query=idea%20diseno&position=23 -'>freepik</a></li>
            <li> <a href='https://pixabay.com/pl/illustrations/widma-koloru-ko%C5%82o-1192509/'>freepik</a></li>



        </ul>
        </div>
    </div>
{% endblock %}

app/templates/page/accessibility.html.twig
{% extends 'base.html.twig' %}

{% block title %}

{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ asset('css/accessibility.css') }}">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&display=swap" rel="stylesheet">
    <script src="https://use.fontawesome.com/ce01bab2aa.js"></script>
{% endblock %}
{% block body %}
    <h1 class="h1">Udogodnienia i dostępność</h1>
    <h2 class="untitle">Dostępność</h2>
    <div class="accessibility">
<div class="section">
    <div class="article">
       <p>Bardzo ważne pojęcie, jednak często pomijane.
        To stopień w jakim dany produkt może być używany przez możliwie największą grupę ludzi.
       </p>

    <p>Dokonując szybkiego podziału, możemy wyróżnić kilka grup, dla których serwis powinien być jednakowo dostępny: </p>
        <ul>
            <li>młodzież/osoby aktywne zawodowo,</li>
            <li>osoby starsze,</li>
            <li>niedowidzący/niewidomi,</li>
            <li>daltoniści.</li>
        </ul>
    <p>Nie możemy także zapomnieć o mniej popularnych przeglądarkach, których użytkownicy też powinni mieć pełen dostęp do serwisu.</p>
        <p>Młodzież/osoby aktywnie zawodowo to zwolennicy przeglądania stron mobilnych, trzeba więc pamietać o optymalizacji wersji dla smartfonów, a najlepiej zaprojektować ją jako pierwszą.
        <p>Osoby starsze, o których często się zapomina, są coraz bardziej aktywne w internecie, więc strony powinny być dla nich dostosowane. Podobnie jak dla osób słabowidzących lub niewidomych.</p>
           <p> Jeśli chodzi o daltonistów, to wystarczy poszperać w Google i można znaleźć strony, na których sprawdzimy, jak oni widzą naszą witrynę.

        </p>
    </div>
</div>
    <h3 class="center">Powiększanie tekstu</h3>
    <div class="sectiontwo">
        <div class="articletwo">
           <p> Autor serwisu internetowego powinien umożliwić odbiorcom zmianę rozmiaru jej elementów.
            Każda strona powinna pozwalać na conajmniej dwukrotne zmiejszenie i powiększenie tekstu. Można zezwolić także na większe powiększenia, ale trzeba liczyć się z tym, że zawartość strony nie będzie wyglądać idealnie.
           </p>
        </div>
        <img class="photo"   src="{{ asset('images/zoom.png') }}" alt=""/>
    </div>
    <h3 class="center">Tekst alternatywny</h3>
    <div class="section">
        <div class="article">
           <p> Każdy obrazek umieszczony na stronie powinien zawierać atrybut alt, czyli tekst alternatywny. Użycie tego atrybutu jest ważne, ponieważ, gdy obrazek się nie załaduje, użytkownik otrzyma wiadomość, co się na nim znajdowało.</p>
            <p> Teksty alterntywne są też ważne dla osób korzystających z czytnika strony internetowej, dzięki użyciu alt osoba ta usłyszy opis tego, co normalnie widziałaby na stronie.</p>
               <p> Jest jeden wyjątek w stosowaniu atrybutu alt, nie uzupełniamy go wtedy, gdy obrazek/zdjęcie pełni funkcję czysto dekoracyjną. W tym wypadku powinien on wyglądać tak: alt="". Dla osób z czytnikiem jest to sygnał, że w tym miejscu znajduje się grafika, lecz nie wpływa na całościowy odbiór strony.
           </p>
        </div>
        <img class="photo"   src="{{ asset('images/zyrafa.png') }}" alt=""/>
    </div>


    <h3 class="center">Klawiatura</h3>
    <div class="section">
        <div class="article">
            <p>Pamiętaj o zapewnieniu dostępu do całej zawartości strony za pomocą klawiatury. Nie każdy może kozystać z myszy.</p>
            <p>W takim porusznaiu pomaga odpowiednie dostosowanie selektora focus w CSS.</p>
        </div>

    </div>
        <h3 class="center">Kontrast</h3>
        <div class="sectiontwo">
            <img class="photo"   src="{{ asset('images/kontrast.png') }}" alt=""/>
            <div class="articletwo">
                <p>Zadbaj o zapewnienie odpowiedniego kontrastu między tekstem a tłem. Nie używaj kolorów, które w połączeniu ze sobą dają bardzo niski współczynnik kontrastu.</p>
                <p>Test kontrastu możesz wykonać na wielu stronach, np.: <a href="https://webaim.org/resources/contrastchecker/">webaim.org</a></p>
            </div>

        </div>
    <h3 class="center">Nagłówki</h3>
    <div class="section">
        <div class="article">
        <p>Bardzo ważne jest również stosowanie odpowiednich nagłówków HTML. </p>
            <p>Standardowe nagłówki HTML to cenną informację o strukturze logicznej treści, ułatwia to korzystanie
            ze strony osobom posługującym się czytnikiem ekranu, choćby dzięki ułatwieniu nawigacji za pomocą klawiatury.
                Używaj elementu h1 w odniesieniu do tytułu strony lub nagłówka dotyczącego głównej treści;
                elementu h2 do nagłówków drugiego stopnia, h3 dla nagłówków pomocniczych i tak dalej. </p>
           <p>Wygląd poszczególnych nagłówków modyfikuj za pomocą CSS.</p>

        </div>

    </div>

    <h3 class="center">Formularze</h3>
    <div class="section">
        <div class="article">
            <p>Przystosuj formularze do pracy z czytnikami ekranu. </p>
            <p>Najlepiej sprawdzi się do tego jeden z elementów HTML "label", którego zadaniem będzie kojarzenie pól z ich opisami.
            Dzięki temu osoby niepełnosprawne będą wiedzieć, co mają wpisać w kolejne pola formularza.
            </p>
        </div>
        <img class="photo"   src="{{ asset('images/formularz.png') }}" alt=""/>
    </div>
    </div>
{% endblock %}

app/templates/page/homepage.html.twig
{% extends 'base.html.twig' %}

{% block title %}

{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ asset('css/home.css') }}">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&display=swap" rel="stylesheet">
    <script src="https://use.fontawesome.com/ce01bab2aa.js"></script>
{% endblock %}
{% block body %}



    <div class="artictletitle">
        <h1 class="box">UX Design</h1>

    </div>


    <div class="main">
        <h2 class="untitle">Czym jest UX Design?</h2>
<div class="sectionone">
    <div class="article"><p>User Experience Design (w skrócie UX/UXD), to projektowanie doświadczeń użytkownika, dbanie o to, aby produkt wzbudzał pozytywne emocje w osobach, które z niego korzystają̨.</p> <p> Tego terminu używa się w odniesieniu do różnych tworów, takich jak:</p>

        <ul>
        <li>strony internetowe,</li>
        <li>aplikacje mobilne/desktopowe,</li>
        <li>produkty fizyczne,</li>
        <li>usługi.</li>
    </ul>

    </div>
        <div class="photo" >
            <img class="ux" id="uxdef" src="{{ asset('images/uxdesign.jpeg') }}" alt="zdjęcie ozdobne"/>
        </div>
</div>
    <h2 class="untitle">Dlaczego UX Design jest tak ważny?</h2>
        <div class="sectionone">
            <div class="photo">
                <img class="ux" id="uxdef" src="{{ asset('images/human.jpeg') }}" alt="ręce"/>

            </div>
            <div class="article"> <p>Każdy użytkownik oczekuje technologii, która jest łatwa w obsłudze i spełnia swoją rolę. UX Design skoncentrowany jest na ludziach, a to oni decydują o sukcesie aplikacji lub strony internetowej.</p>
<p>Jakość doświadczeń użytkownika podczas interakcji z produktem jest kluczowa. UX Design uwzględnia potrzeby użytkowników na wszystkich etapach projektowania. Projektanci UX wykorzystują specjalne badania oraz testy. Wszystko po to, by określić, czego oczekują użytkownicy (cech, funkcji, walorów estetycznych).</p>
</div>
        </div>
   <h2 class="untitle">Czym zajmują się UX designerzy?</h2>
        <div class="sectionone">
<div class="article">
    <p>UX designerzy są odpowiedzialni za przyjazność i dostępność tworzonych produktów, usług i technologii.

        Projektant UX nie ma gotowego przepisu, jak sprawić, by użytkownicy byli zadowoleni. Jednak można wyszczególnić działania, które są stałe, by do tego celu dążyć.</p>

    <p>Kilka powszechnych działań UX designerów:</p>
    <ul class="list">
        <li>poprawa istniejącego systemu,</li>
        <li>testy AB,</li>
        <li>prototypowanie,</li>
        <li>ankiety,</li>
        <li>wireframing,</li>
        <li>mapa przejść użytkownika (user flow),</li>
        <li>wzorce projektowe,</li>
        <li>persony.</li>

    </ul>

</div>
            <div class="photo">
                <img class="ux" id="uxdef" src="{{ asset('images/designer.jpeg') }}" alt="ux designer"/>

            </div>
        </div>

   <h2 class="untitle">UX a UI</h2>
        <div class="sectionone">
            <div class="photo">
                <img class="ux" id="uxdef" src="{{ asset('images/uxvsui.jpeg') }}" alt="ux designer"/>

            </div>
<div class="article">
   <p> Projektowanie UX jest powiązane z projektowaniem UI, ale różni się od niego.</p>
    <p>UI (User Interface) skupia się na tym, jak produkt wygląda i działa, bez szczególnego uwzględniania preferencji użytkownika.</p> <p>Projektant UI stosuje wiedzę z zakresu estetyki do elementów wizualnych produktu, takich jak:</p>
    <ul class="list">
        <li>animacje,</li>
        <li>przyciski,</li>
        <li>pola wyboru,</li>
        <li>paleta kolorów,</li>
        <li>diagramy,</li>
        <li>obrazy,</li>
        <li>typografia,</li>
        <li>widżety.</li>

    </ul>
    <p>Projektant UX stosuje wiedzę o tym, czego chcą i potrzebują użytkownicy, do działań i funkcji produktu.</p>
    <p class="end">  Współpraca projektantów UX i UI ostatecznie tworzy najlepszy możliwy produkt poprzez połączenie formy i funkcji.
    </p>



    </div>


    </div>
{% endblock %}

app/templates/question/score.html.twig
{% extends 'base.html.twig' %}

{% block title %}

{% endblock %}

{% block body %}
   <h1 class="score">Twój wynik to: {{ counter }}/30 punktów</h1>

{% endblock %}

app/templates/question/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}

{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ asset('css/quiz.css') }}">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&display=swap" rel="stylesheet">
    <script src="https://use.fontawesome.com/ce01bab2aa.js"></script>
{% endblock %}
{% block body %}

    <div class="quiz">




            {% for question in question %}

                {% if question.id==1 %}
               <h1 class="quizname">{{ question.quiz.name }}</h1>
                {% endif %}
           <h1 class="pytanie">{{ 'Pytanie ' }}{{ question.id }}</h1> <h2>{{ question.content }}</h2>


            <form  method="post" action="{{ url('sendQuiz') }}">

                {% for questionPossibleAnswer in question.questionPossibleAnswer %}
<div >
                <label class="rad-label"  for="{{ questionPossibleAnswer.id }}">
               <input class="rad-input"  id="{{ questionPossibleAnswer.id }}" type="radio" value="{{ questionPossibleAnswer.isCorrect }}" name="{{ questionPossibleAnswer.question.id }}">
                    <div class="rad-design"></div>
                    <div class="rad-text">{{ questionPossibleAnswer.content }}</div>


                    </label>
</div>
            {% endfor %}


            {% endfor %}
                <div class="wrapper"><input type="submit" value="Zakończ"></div>
            </form>

 <div>

 </div>

    </div>

{% endblock %}